# -*- coding: utf-8 -*-
"""CO1-AT1-Q08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZa72cEp66VnPvOPoRzkD-sidxrHvYIs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a synthetic grayscale image
img = np.zeros((200, 200), dtype=np.uint8)
cv2.circle(img, (100, 100), 50, 180, -1)

# Step 2: Add Gaussian noise (simulating sensor noise)
noise = np.random.normal(0, 25, img.shape).astype(np.int16)
noisy = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)

# Step 3: Remove noise using Gaussian Blur
denoised = cv2.GaussianBlur(noisy, (5, 5), 0)

# Step 4: Display images
plt.figure(figsize=(10,4))

plt.subplot(1,3,1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(noisy, cmap='gray')
plt.title("Noisy Image")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(denoised, cmap='gray')
plt.title("Noise Reduced")
plt.axis('off')

plt.show()