# -*- coding: utf-8 -*-
"""CO1-AT1-Q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZa72cEp66VnPvOPoRzkD-sidxrHvYIs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a synthetic high-resolution image
img = np.zeros((256, 256), dtype=np.uint8)
cv2.circle(img, (128, 128), 60, 255, -1)

# Step 2: Downsample (simulate low-resolution image)
low_res = cv2.resize(img, (64, 64), interpolation=cv2.INTER_AREA)

# Step 3: Upsample back for display
restored = cv2.resize(low_res, (256, 256), interpolation=cv2.INTER_NEAREST)

# Step 4: Display images
plt.figure(figsize=(9,3))

plt.subplot(1,3,1)
plt.imshow(img, cmap='gray')
plt.title("High Resolution")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(low_res, cmap='gray')
plt.title("Low Resolution")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(restored, cmap='gray')
plt.title("Upsampled Image")
plt.axis('off')

plt.show()