# -*- coding: utf-8 -*-
"""CO1-AT1-Q07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZa72cEp66VnPvOPoRzkD-sidxrHvYIs
"""

import cv2                              # Import OpenCV
import numpy as np                      # Import NumPy
import matplotlib.pyplot as plt         # Import Matplotlib

# Step 1: Create a grayscale gradient image
img = np.tile(np.linspace(0, 255, 256, dtype=np.uint8), (100, 1))

# Step 2: Quantize the image to 4 gray levels
levels = 4
quantized = (img // (256 // levels)) * (256 // levels)

# Step 3: Display the original and quantized images
plt.figure(figsize=(8,4))

plt.subplot(1,2,1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(quantized, cmap='gray')
plt.title("Quantized Image (4 Levels)")
plt.axis('off')

plt.show()