# -*- coding: utf-8 -*-
"""CO1-AT1-Q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5OPK0Vy6JVZ80HihSPxYxpx7mOscWY1
"""

import cv2
import matplotlib.pyplot as plt

# Read the image
image = cv2.imread('/content/low_light.jpg')

# Check if image is loaded
if image is None:
    print("Error: Image not found!")
else:
    # Convert BGR to RGB
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Enhance brightness and contrast
    enhanced = cv2.convertScaleAbs(image_rgb, alpha=1.5, beta=40)

    # Display original and enhanced images
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(image_rgb)
    plt.title("Original Low-Light Image")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(enhanced)
    plt.title("Enhanced Image")
    plt.axis("off")

    plt.show()