# -*- coding: utf-8 -*-
"""CO1-AT1-Q06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZa72cEp66VnPvOPoRzkD-sidxrHvYIs
"""

import cv2                              # Import OpenCV
import numpy as np                      # Import NumPy
import matplotlib.pyplot as plt         # Import Matplotlib

# Step 1: Create a synthetic low-quality image
img = np.zeros((200, 200), dtype=np.uint8)
cv2.rectangle(img, (50, 50), (150, 150), 120, -1)

# Step 2: Add Gaussian noise
noise = np.random.normal(0, 25, img.shape).astype(np.int16)
noisy = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)

# Step 3: Reduce noise using Gaussian Blur
denoised = cv2.GaussianBlur(noisy, (5, 5), 0)

# Step 4: Improve contrast using Histogram Equalization
enhanced = cv2.equalizeHist(denoised)

# Step 5: Display Results
plt.figure(figsize=(10,4))

plt.subplot(1,3,1)
plt.imshow(noisy, cmap='gray')
plt.title("Noisy Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(denoised, cmap='gray')
plt.title("After Noise Removal")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(enhanced, cmap='gray')
plt.title("Enhanced Image")
plt.axis('off')

plt.show()