# -*- coding: utf-8 -*-
"""CO1-AT1-Q04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZa72cEp66VnPvOPoRzkD-sidxrHvYIs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Create a grayscale gradient image (8-bit, 256 intensity levels)
img = np.tile(np.linspace(0, 255, 256, dtype=np.uint8), (100, 1))

# Quantize the image to 3-bit (8 intensity levels)
quantized = np.floor(img / 32) * 32
quantized = quantized.astype(np.uint8)

# Display the original and quantized images
plt.figure(figsize=(8, 4))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title('Original (8-bit, 256 Levels)')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(quantized, cmap='gray')
plt.title('Quantized (3-bit, 8 Levels)')
plt.axis('off')

plt.show()